#
# Build configuration for Circle CI
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha
    steps:
      - checkout
      - run: ./android && ./gradlew assembleRelease
