version: 2
jobs:
  test:
    docker:
      - image: circleci/android:api-28-alpha  # gcloud is baked into this image
    steps:
      - run:
          name: Build debug APK and release APK
          command: |
            ./android/gradlew :app:assembleDebug
            ./android/gradlew :app:assembleDebugAndroidTest
      - run:
          name: Store Google Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Authorize gcloud and set config defaults
          command: |
            sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}

  deployment:
    environment:
      SR_DEV: dev
      SR_DEV_URL: dev.seersite.com
      SR_DEV_DB_URL: db url should be provided

    steps:
      - checkout
      - run:
          name: choose environment
          command:
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                ansible-playbook site.yml
            fi



workflows:
  version: 2
  workflow-name:
    jobs:
      - test